#!/bin/bash

BAKEFILES=${PWD}/bakefiles.zip

if [ -e $BAKEFILES ]
then
	# move to the home directory and get the source comressed archive for wxBase
	cd ~
	wget http://sourceforge.net/projects/wxwindows/files/2.8.12/wxBase-2.8.12.tar.gz
	tar -xzvf wxBase-2.8.12.tar.gz

	# move into the directory, configure and build it
	cd wxBase-2.8.12
	./configure --disable-gui --without-expat
	make

	# add the bakefiles and install wxBase
	cd build
	unzip $BAKEFILES
	cd ..
	sudo make install

	# add /usr/local/lib to /etc/ld.so.conf, if needed and relink the libraries
	sudo ldconfig -v
	
	echo "==================================================="
	echo "wxBase compiled and installed!"
	echo "Inspect the 'ldconfig -v' output above to make sure that the wx libraries"
	echo "are showing up in the /usr/local/lib directory."
else
	echo "$BAKEFILES not found, aborting!"
fi
