#!/bin/bash
#
# Copyright (c) 2019 by Thomas A. Early N7TAE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

trap ControlC INT

ControlC () {
	echo "caught SIGINT"
}

InstallSystem () {
	local n
	if [ -z ${1} ]; then
		n=$( grep processor /proc/cpuinfo | wc -l )
		echo "Detected $n processors for make"
		make base -j$n
	fi
	sudo make ${1}installbase
	if [ $ndvap -gt 0 ]; then
		if [ -z ${1} ]; then
			make qndvap -j$n
		fi
		if [ $ndvap -eq 1 ]; then
			sudo make ${1}installdvap
		else
			sudo make MODULE=$advap[0] ${1}installdvap
			sudo make MODULE=$advap[1] ${1}installdvap
			if [ $ndvap -eq 3 ]; then
				sudo make MODULE=$advap[2] ${1}installdvap
			fi
		fi
	fi
	if [ $ndvrptr -gt 0 ]; then
		if [ -z ${1} ]; then
			make qndvrptr -j$n
		fi
		if [ $ndvrptr -eq 1 ]; then
			sudo make ${1}installdvrptr
		else
			sudo make MODULE=$advrptr[0] ${1}installdvrptr
			sudo make MODULE=$advrptr[1] ${1}installdvrptr
			if [ $ndvrptr -eq 3 ]; then
				sudo make MODULE=$advrptr[2] ${1}installdvrptr
			fi
		fi
	fi
	if [ $nitap -gt 0 ]; then
		if [ -z ${1} ]; then
			make qnitap -j$n
		fi
		if [ $nitap -eq 1 ]; then
			sudo make ${1}installitap
		else
			sudo make MODULE=$aitap[0] ${1}installitap
			sudo make MODULE=$aitap[1] ${1}installitap
			if [ $nitap -eq 3 ]; then
				sudo make MODULE=$aitap[2] ${1}installitap
			fi
		fi
	fi
	if [ $nmmdvm -gt 0 ]; then
		if [ -z ${1} ]; then
			make qnrelay -j$n
		fi
		if [ $nmmdvm -eq 1 ]; then
			sudo make ${1}installrelay
		else
			sudo make MODULE=$ammdvm[0] ${1}installrelay
			sudo make MODULE=$ammdvm[1] ${1}installrelay
			if [ $nmmdvm -eq 3 ]; then
				sudo make MODULE=$advap[2] ${1}installrelay
			fi
		fi
	fi
}

BaseStatus () {
	local LoadGate SubGate LoadLink SubLink LoadDTMF SubDTMF
	LoadGate=$( systemctl show -p LoadState --value qngateway )
	SubGate=$( systemctl show -p SubState --value qngateway )
	LoadLink=$( systemctl show -p LoadState --value qnlink )
	SubLink=$( systemctl show -p SubState --value qnlink )
	LoadDTMF=$( systemctl show -p LoadState --value qndtmf )
	SubDTMF=$( systemctl show -p SubState --value qndtmf )
	if [[ $LoadGate == 'loaded' ]]; then
		if [[ $SubGate == 'running' ]]; then
			GateState='running'
		else
			GateState='stopped'
		fi
	else
		GateState='not installed'
	fi
	echo "QetGateway is $GateState"
	if [[ $LoadLink == 'loaded' ]]; then
		if [[ $SubLink == 'running' ]]; then
			LinkState='running'
		else
			LinkState='stopped'
		fi
	else
		LinkState='not installed'
	fi
	echo "QetLink is $LinkState"
	if [[ $LoadDTMF == 'loaded' ]]; then
		if [[ $SubDTMF == 'running' ]]; then
			DTMFState='running'
		else
			DTMFState='stopped'
		fi
	else
		DTMFState='not installed'
	fi
	echo "DTMF is $DTMFState"
}

ModuleStatus () {
	local LoadState SubState mcvar process
	if [ -z ${3} ]; then
		ModuleState[$1]='EMPTY'
	else
		mcvar="n${3}"
		process="qn$3"
		if [[ "$process" == 'qnmmdvm' ]]; then process='qnrelay'; fi
		if [[ ${!mcvar} > 1 ]]; then
			process="${process}${2}"
		fi
		LoadState=$( systemctl show -p LoadState --value $process )
		SubState=$( systemctl show -p SubState --value $process )
		if [[ "$LoadState" == "loaded" ]]; then
			if [[ $SubState == "running" ]]; then
				ModuleState[$1]='running'
			else
				ModuleState[$1]='stopped'
			fi
		else
			ModuleState[$1]='not installed'
		fi
		echo "Module ${2^^} - ${3^^} is ${ModuleState[$1]}"
	fi
}

GetModuleProcess () {
	local nvar
	process=$1
	nvar="n$process"
	if [[ $process == 'mmdvm' ]]; then
		process='relay'
	fi
	process="qn$process"
	if [ ${!nvar} -gt 1 ]; then
		process=${process}${1}
	fi
}

LogMenu () {
	ans=''
	while [[ "$ans" != q* ]]; do
		clear
		echo "            Log Menu"
		echo
		echo "After starting a log, use <Ctrl>+C to stop the log and return to this menu."
		echo
		if [[ $GateState == 'running' ]]; then
			echo " g  : qngateway Log"
		else
			echo "      qngateway is not running"
		fi
		if [[ $LinkState == 'running' ]]; then
			echo " l  : qnlink Log"
		else
			echo "      qnlink is not running"
		fi
		if [[ $DTMFState == 'running' ]]; then
			echo " d  : qndtmf Log"
		else
			echo "      qndtmf is not running"
		fi
		if [[ ${ModuleState[0]} != 'EMPTY' ]]; then
			GetModuleProcess $module_a
			if [[ ${ModuleState[0]} == 'running' ]]; then
				echo " a  : $process Log"
			else
				echo "      $process is not running"
			fi
		fi
		if [[ ${ModuleState[1]} != 'EMPTY' ]]; then
			GetModuleProcess $module_b
			if [[ ${ModuleState[1]} == 'running' ]]; then
				echo " b  : $process Log"
			else
				echo "      $process is not running"
			fi
		fi
		if [[ ${ModuleState[2]} != 'EMPTY' ]]; then
			GetModuleProcess $module_c
			if [[ ${ModuleState[2]} == 'running' ]]; then
				echo " c  : $process Log"
			else
				echo "      $process is not running"
			fi
		fi
		echo
		echo " q  : quit and return to main menu"
		echo
		read -p "Command: " ans

		if [[ "$ans" == g* ]] && [[ "$GateState" == 'running' ]]; then
			sudo journalctl -u qngateway -f
		elif [[ "$ans" == l* ]] && [[ "$LinkState" == 'running' ]]; then
			sudo journalctl -u qnlink -f
		elif [[ "$ans" == d* ]] && [[ "$DTMFState" == 'running' ]]; then
			sudo journalctl -u qndtmf -f
		elif [[ "$ans" == a* ]] && [[ "${ModuleState[0]}" == 'running' ]]; then
			GetModuleProcess $module_a
			sudo journalctl -u $process -f
		elif [[ "$ans" == b* ]] && [[ "${ModuleState[1]}" == 'running' ]]; then
			GetModuleProcess $module_b
			sudo journalctl -u $process -f
		elif [[ "$ans" == c* ]] && [[ "${ModuleState[2]}" == 'running' ]]; then
			GetModuleProcess $module_c
			sudo journalctl -u $process -f
		fi
	done
	ans=
}

MaintenanceMenu () {
	local m n
	ans=''
	while [[ "$ans" != q* ]]; do
		clear
		echo "            MaintenanceMenu"
		echo
		if [[ "$GateState" == 'running' ]]; then
			echo " g : Stop  QnetGateway"
		elif [[ "$GateState" == 'stopped' ]]; then
			echo " g : Start QnetGateway"
		fi
		if [[ "$LinkState" == 'running' ]]; then
			echo " l : Stop  QnetLink"
		elif [[ "$LinkState" == 'stopped' ]]; then
			echo " l : Start QnetLink"
		fi
		if [[ "$DTMFState" == 'running' ]]; then
			echo " d : Stop  DTMF"
		elif [[ "$DTMFState" == 'stopped' ]]; then
			echo " d : Start DTMF"
		fi
		if [[ "${ModuleState[0]}" == 'running' ]]; then
			echo " a : Stop Module A"
		elif [[ "${ModuleState[0]}" == 'stopped' ]]; then
			echo " a : Start Module A"
		fi
		if [[ "${ModuleState[1]}" == 'running' ]]; then
			echo " b : Stop Module B"
		elif [[ "${ModuleState[1]}" == 'stopped' ]]; then
			echo " b : Start Module B"
		fi
		if [[ "${ModuleState[2]}" == 'running' ]]; then
			echo " c : Stop Module C"
		elif [[ "${ModuleState[2]}" == 'stopped' ]]; then
			echo " c : Start Module C"
		fi
		echo
		echo " q : Return to main Menu"
		echo
		read -p "Command: " ans

		if   [[ "$ans" == g* ]]; then
			if [[ "$GateState" == 'running' ]]; then
				sudo systemctl stop qngateway
			elif [[ "$GateState" == 'stopped' ]]; then
				sudo systemctl start qngateway
			fi
		elif [[ "$ans" == l* ]]; then
			if [[ "$LinkState" == 'running' ]]; then
				sudo systemctl stop qnlink
			elif [[ "$LinkState" == 'stopped' ]]; then
				sudo systemctl start qnlink
			fi
		elif [[ "$ans" == d* ]]; then
			if [[ "$DTMFState" == 'running' ]]; then
				sudo systemctl stop qndtmf
			elif [[ "$DTMFState" == 'stopped' ]]; then
				sudo systemctl start qndtmf
			fi
		elif [[ "$ans" == a* ]] && [ -n $module_a ]; then
			GetModuleProcess $module_a
			if [[ "${ModuleState[0]}" == 'running' ]]; then
				sudo systemctl stop $process
			elif [[ "${ModuleState[0]}" == 'stopped' ]]; then
				sudo systemctl start $process
			fi
			ModuleState 0 a $module_a
		elif [[ "$ans" == b* ]] && [ -n $module_b ]; then
			GetModuleProcess $module_b
			if [[ "${ModuleState[1]}" == 'running' ]]; then
				sudo systemctl stop $process
			elif [[ "${ModuleState[1]}" == 'stopped' ]]; then
				sudo systemctl start $process
			fi
			ModuleState 1 b $module_b
		elif [[ "$ans" == c* ]] && [ -n $module_c ]; then
			GetModuleProcess $module_c
			if [[ "${ModuleState[2]}" == 'running' ]]; then
				sudo systemctl stop $process
			elif [[ "${ModuleState[2]}" == 'stopped' ]]; then
				sudo systemctl start $process
			fi
			ModuleState 2 c $module_c
		fi
		BaseState
	done
	ans=''
}

# get defined modules from the config file
if [ -e qn.cfg ]; then
	source <( grep "^module_[abc]=" qn.cfg )
	if [ -z "$module_a" ] && [ -z "$module_b" ] && [ -z "$module_c" ]; then
		echo "No moudules defined in the qn.cfg file!, please re-edit you configuration."
		exit 1
	fi
else
	echo "ERROR: can't find the qn.cfg configuration file!"
	echo "You can use ./qnconfig to create your config file."
	exit 1
fi

# get the installation directory from the make file
if [ -e makefile ]; then
	MAKEFILE=makefile
elif [ -e Makefile ]; then
	MAKEFILE=Makefile
else
	echo "ERROR: There is no Makefile or makefile"
	exit 1
fi
source <( grep "^BINDIR=" $MAKEFILE )
if [ -z $BINDIR ]; then
	echo "ERROR: The BINDIR definition in $MAKEFILE is empty!"
	exit 1
fi
if [ ! -d "$BINDIR" ]; then
	echo "ERROR: The BINDIR directory $BINDIR is not a directory!"
	exit 1
fi

ndvap=0
ndvrptr=0
nitap=0
nmmdvm=0

for m in a b c ; do
	mod=module_${m}
	if [ -z ${!mod} ]; then continue; fi
	type=${!mod}
	if [[ "$type" == 'dvap' ]]; then
		advap[${ndvap}]=${m}
		ndvap=$((ndvap + 1))
	elif [[ "$type" == 'dvrptr' ]]; then
		advrptr[$ndvap]=${m}
		ndvrptr=$((ndvrptr + 1))
	elif [[ "$type" == 'itap' ]]; then
		aitap[${nitap}]=${m}
		nitap=$((nitap + 1))
	elif [[ "$type" == 'mmdvm' ]]; then
		ammdvm[${nmmdvm}]=${m}
		nmmdvm=$((nmmdvm + 1))
	fi
done

MODULE_COUNT=$((ndvap + ndvrptr + nitap + nmmdvm))

while [[ "$ans" != q* ]]; do
	clear
	echo
	echo "            Qnet Administration Menu"
	echo
	BaseStatus
	ModuleStatus 0 a "$module_a"
	ModuleStatus 1 b "$module_b"
	ModuleStatus 2 c "$module_c"
	echo
	if [[ "$GateState" == 'not installed' ]] || [[ "$LinkState" == 'not installed' ]]; then
		echo "is : Install configured system"
	else
		echo "us : Uninstall configured System"
	fi
	if [[ "$DTMFState" == 'not installed' ]]; then
		echo "id : Install DTMF"
	else
		echo "ud : Uninstall DTMF"
	fi
	echo "c  : Clean (remove temporary files and locally built executables)"
	echo
	if [[ "$GateState" != 'not installed' ]] && [[ "$LinkState" != 'not installed' ]]; then
		echo "m  : Maintenance Menu"
		echo "l  : Log Menu"
	fi
	echo
	read -p "q  to quit. Command: " ans

	# EXECUTE COMMANDS
	if   [[ "$ans" == is* ]]; then
		InstallSystem
	elif [[ "$ans" == us* ]]; then
		InstallSystem un
	elif [[ "$ans" == id* ]]; then
		sudo make installdtmf
	elif [[ "$ans" == ud* ]]; then
		sudo make uninstalldtmf
	elif [[ "$ans" == c* ]]; then
		make clean
	elif [[ "$ans" == m* ]]; then
		MaintenanceMenu
	elif [[ "$ans" == l* ]]; then
		LogMenu
	fi
done

exit 0
